jobs:
  - template: azure-windows-build-job-template.yml
    parameters:
      buildConfiguration: Release
  - template: azure-windows-build-job-template.yml
    parameters:
      buildConfiguration: Debug
