parameters:
  buildConfiguration: Release
  name: ''

jobs:
  - job: ${{ parameters.name }}

    pool:
      vmImage: 'VS2017-Win2016'

    timeoutInMinutes: 120

    steps:
    - script: git clone -b release_60 https://github.com/llvm-mirror/llvm $(Build.ArtifactStagingDirectory)/llvm

    - task: CMake@1
      inputs:
        workingDirectory: '$(Build.ArtifactStagingDirectory)/llvm/build'
        cmakeArgs: '-G "Visual Studio 15 2017 Win64" -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_GO_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_OPTIMIZED_TABLEGEN=ON $(Build.ArtifactStagingDirectory)/llvm'

    - task: VSBuild@1
      inputs:
        solution: '$(Build.ArtifactStagingDirectory)/llvm/build/LLVM.sln'
        platform: x64
        configuration: ${{ parameters.buildConfiguration }}

    - task: CMake@1
      inputs:
        workingDirectory: '$(Build.ArtifactStagingDirectory)/build'
        cmakeArgs: '-G "Visual Studio 15 2017 Win64" -DLLVM_DIR=$(Build.ArtifactStagingDirectory)/llvm/build/lib/cmake/llvm $(Build.SourcesDirectory)'

    - task: VSBuild@1
      inputs:
        solution: '$(Build.ArtifactStagingDirectory)/build/WAVM.sln'
        platform: x64
        configuration: ${{ parameters.buildConfiguration }}

    - script: |
        cd $(Build.ArtifactStagingDirectory)/build
        ctest -V