jobs:
  - template: azure-windows-build-job-template.yml
    parameters:
      name: Windows Release
      buildConfiguration: Release
  - template: azure-windows-build-job-template.yml
    parameters:
      name: Windows Debug
      buildConfiguration: Debug
